Add login page
ilyayudovin/spring pull request #2
Opened 2020-10-07 20:12 UTC by ilyayudovin

2020-10-12 09:51 UTC, IAmVisco requested changes

2020-10-12 09:51 UTC, IAmVisco commented on package.json
> +    "-": "0.0.1",
Are you kidding me

2020-10-12 09:51 UTC, IAmVisco commented on package.json
> +    "save-dev": "0.0.1-security"
Same as above.

2020-10-12 09:51 UTC, IAmVisco commented on src/components/Login/Login.js
> +import {useHistory} from 'react-router-dom';
ESlint broke.

2020-10-12 09:51 UTC, IAmVisco commented on src/components/Login/Login.js
> +    if(password !== '1234'){
ESlint broke.

2020-10-12 09:51 UTC, IAmVisco commented on src/components/Login/Login.js
> +        <form onSubmit={handleSubmit(onSubmit)}>
Weird naming chain.

2020-10-12 09:51 UTC, IAmVisco commented on src/components/Login/Login.js
> +              className={errors.username && "wrongInput" }
Extra space.

2020-10-12 09:51 UTC, IAmVisco commented on src/components/Login/Login.js
> +            {errors.username?.type === "wrong" && <p className="errorMessage">username field is incorrect</p>}
Capitalize first letter of the error message.

2020-10-12 09:51 UTC, IAmVisco commented on src/components/Login/Login.js
> +  const handlePassword = () => {
`handle`?

2020-10-12 09:52 UTC, IAmVisco commented
Has 0 security whatsoever.
Add logout button.

2020-10-13 14:35 UTC, IAmVisco requested changes

2020-10-13 14:35 UTC, IAmVisco commented on src/components/Login/Login.js
> +  const passwordVisibility = () => {
Missing a verb. Functions are actions, actions are usually represented as verbs.

2020-10-13 14:35 UTC, IAmVisco commented on src/components/Login/Login.js
> +        <form onSubmit={handleSubmit(onSubmit)}>
Still not fixed.

2020-10-13 14:35 UTC, IAmVisco commented on src/components/Navigation/Navigation.js
> +    localStorage.setItem('isAuthorized', 'false');
Usually done by just deleting entry.

2020-10-13 14:35 UTC, IAmVisco commented on src/index.js
> +    console.log('false');
Do not commit console logs. Add esling rule to disallow console logs whatsoever. (I thought Airbnb ruleset has it?)

2020-10-13 14:35 UTC, IAmVisco commented on src/index.js
> +       )}/>
I think it's not the correct flow. Create a component called `<AuthorizedRoute />` and do checks there. There are a ton of tutorials for such route wrappers.

2020-10-13 17:20 UTC, IAmVisco requested changes

2020-10-13 17:20 UTC, IAmVisco commented on src/components/Login/Login.js
> +  const ChangePasswordVisibility = () => {
Function names are written starting with lower case letters. Capitalized function are React components.

2020-10-13 17:22 UTC, ilyayudovin commented on src/components/Login/Login.js
> +  const ChangePasswordVisibility = () => {
Oops

2020-10-14 19:45 UTC, merged